### ISSUE TITLE
Unique Identifiers

### ISSUE THREAD

**Issue by Kaschman** [Combine-Labs/schemas#8]
SD has a specific SD SKU

Do we use UPCs?

**Comment by cmbirk** [comment]
We likely will have both. Taking a look at [schema.org/product](https://schema.org/Product) It looks like a UPC would be a `gtin` value, whereas `sku` has its own attribute as vendor-specific.

**Comment by cmbirk** [comment]
Added to the product schema.

**Comment by cmbirk** [comment]
I think this is in reference to a product-level sku

**Comment by jrphilo** [comment]
We will almost certainly want to have https://en.wikipedia.org/wiki/International_Article_Number built in somehow, and because this is mapping to the SD stuff, we will need to figure out how to map from an EAN (public standard) to SD's internal SKU (purely an SD product ID).

I do not know how an EAN gets built up.

An SD SKU is built along the lines of 0011223344

`00` Department
`11` Category
`22` Style
`33` Color
`44` Size

This is not exactly right but close enough to give you a gist.

@Kaschman @cmbirk

**Comment by jrphilo** [comment]
Please make sure with some of these questions you queue them up in a questions list to talk to people (like Dave Barton) about so we are matching existing accepted practices where relevant

**Comment by cmbirk** [comment]
Yep. Regular SKU fits for SD-specific here. Will open a ticket for the International Article Number

**Comment by Kaschman** [comment]
ok it looks like GTIN is a 12 digit code, IAN is a 13 digit code
https://www.gs1uk.org/our-industries/retail/selling-on-marketplaces/ultimate-guide-to-gtins-eans-and-upcs-for-amazon-ebay-google
you can convert GTIN to IAN by adding a 0 - should we be saving everything as IAN?

**Comment by Kaschman** [comment]
oh hang on - Schema.org has this. https://schema.org/gtin
a 13-digit number is an IAN, a 12 digit number is a GTIN

**Comment by Kaschman** [comment]
what path specifically? Seems to me we need to add a 'gtin' field that can take a 12 or 13 digit numeric value and serves as a unique identifier for a product

**Comment by cmbirk** [comment]
I believe GTIN codes are specifically assigned from GS1 ( see https://schema.org/gtin12 ). They aren't any generic 12 or 13 digit values. We can use a different identifier for a non-GS1 code.

**Comment by Kaschman** [comment]
we need GTIN for sure
the SKU is an internal identifier from the *seller* whether it is a marketplace seller or SD - it is the *owner of the inventory*

should SKU be a part of inventory?

SD SKU is optional (check on this with RC/Bob's)
unsure if seller SKU needs to be included
